/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI;

import CLASS.ChucVu;
import CLASS.PhongBan;
import DAO.ChucVuDAO;
import DAO.PhongBanDAO;
import DAO.ThongKeDAO;
import UTILS.Auth;
import UTILS.Msgbox;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zander
 */
public class Statistics extends javax.swing.JInternalFrame {

    /**
     * Creates new form Statistics
     */
    public Statistics() {
        initComponents();
        setTitle("Thống kê số liệu");
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lblUv = new javax.swing.JLabel();
        cboCv = new javax.swing.JComboBox<>();
        btnUv = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUngVien = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblMinTuoi = new javax.swing.JLabel();
        txtMinTuoi = new javax.swing.JTextField();
        lblMaxTuoi = new javax.swing.JLabel();
        txtMaxTuoi = new javax.swing.JTextField();
        btnTuoi = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblTuoi = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lblMinLuong = new javax.swing.JLabel();
        txtMinLuong = new javax.swing.JTextField();
        txtMaxLuong = new javax.swing.JTextField();
        lblMaxLuong = new javax.swing.JLabel();
        btnLuong = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLuong = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblHopDong = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        lblPb = new javax.swing.JLabel();
        cboPb = new javax.swing.JComboBox<>();
        btnPb = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblPhongBan = new javax.swing.JTable();

        setBackground(new java.awt.Color(235, 223, 235));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(235, 223, 235));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("THỐNG KÊ SỐ LIỆU");

        tabs.setBackground(new java.awt.Color(112, 194, 180));
        tabs.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(112, 194, 180));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel7.setBackground(new java.awt.Color(112, 194, 180));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblUv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUv.setText("Tên chức vụ");

        cboCv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnUv.setBackground(new java.awt.Color(255, 255, 204));
        btnUv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/icons8-search-32.png"))); // NOI18N
        btnUv.setText("Tìm kiếm");
        btnUv.setBorderPainted(false);
        btnUv.setOpaque(true);
        btnUv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUvActionPerformed(evt);
            }
        });

        tblUngVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số lượng ứng viên", "Số lượng PASS", "Số lượng FAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUngVien);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblUv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboCv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUv)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUv)
                    .addComponent(btnUv)
                    .addComponent(cboCv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabs.addTab("ỨNG VIÊN", jPanel2);

        jPanel3.setBackground(new java.awt.Color(112, 194, 180));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel8.setBackground(new java.awt.Color(112, 194, 180));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMinTuoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMinTuoi.setText("Tuổi từ");

        txtMinTuoi.setToolTipText("");

        lblMaxTuoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaxTuoi.setText("đến");

        btnTuoi.setBackground(new java.awt.Color(255, 255, 204));
        btnTuoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTuoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/icons8-search-32.png"))); // NOI18N
        btnTuoi.setText("Tìm kiếm");
        btnTuoi.setBorderPainted(false);
        btnTuoi.setOpaque(true);

        tblTuoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số lượng nhân viên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tblTuoi);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lblMinTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMinTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMaxTuoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaxTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTuoi)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinTuoi)
                    .addComponent(txtMinTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaxTuoi)
                    .addComponent(txtMaxTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTuoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabs.addTab("ĐỘ TUỔI", jPanel3);

        jPanel4.setBackground(new java.awt.Color(112, 194, 180));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel9.setBackground(new java.awt.Color(112, 194, 180));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMinLuong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMinLuong.setText("Lương từ");

        txtMinLuong.setText("10000000");

        lblMaxLuong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaxLuong.setText("đến");

        btnLuong.setBackground(new java.awt.Color(255, 255, 204));
        btnLuong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/icons8-search-32.png"))); // NOI18N
        btnLuong.setText("Tìm kiếm");
        btnLuong.setBorderPainted(false);
        btnLuong.setOpaque(true);

        tblLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số lượng nhân viên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblLuong);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(lblMinLuong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMinLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMaxLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaxLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLuong)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinLuong)
                    .addComponent(txtMinLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaxLuong)
                    .addComponent(txtMaxLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabs.addTab("LƯƠNG", jPanel4);

        jPanel5.setBackground(new java.awt.Color(112, 194, 180));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel10.setBackground(new java.awt.Color(112, 194, 180));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblHopDong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Loại hợp đồng", "Số lượng nhân viên đã ký"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblHopDong);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabs.addTab("HỢP ĐỒNG", jPanel5);

        jPanel6.setBackground(new java.awt.Color(112, 194, 180));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel11.setBackground(new java.awt.Color(112, 194, 180));
        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblPb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPb.setText("Tên phòng ban");

        cboPb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnPb.setBackground(new java.awt.Color(255, 255, 204));
        btnPb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icon/icons8-search-32.png"))); // NOI18N
        btnPb.setText("Tìm kiếm");
        btnPb.setBorderPainted(false);
        btnPb.setOpaque(true);
        btnPb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPbActionPerformed(evt);
            }
        });

        tblPhongBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số lượng nhân viên", "Số lượng chức vụ", "Họ tên trưởng phòng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblPhongBan);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(lblPb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboPb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPb)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPb)
                    .addComponent(btnPb)
                    .addComponent(cboPb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabs.addTab("PHÒNG BAN", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabs)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabs)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPbActionPerformed
        // TODO add your handling code here:
        fillTblPhongBan();
    }//GEN-LAST:event_btnPbActionPerformed

    private void btnUvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUvActionPerformed
        // TODO add your handling code here:
        fillTblUngVien();
    }//GEN-LAST:event_btnUvActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuong;
    private javax.swing.JButton btnPb;
    private javax.swing.JButton btnTuoi;
    private javax.swing.JButton btnUv;
    private javax.swing.JComboBox<String> cboCv;
    private javax.swing.JComboBox<String> cboPb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblMaxLuong;
    private javax.swing.JLabel lblMaxTuoi;
    private javax.swing.JLabel lblMinLuong;
    private javax.swing.JLabel lblMinTuoi;
    private javax.swing.JLabel lblPb;
    private javax.swing.JLabel lblUv;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblHopDong;
    private javax.swing.JTable tblLuong;
    private javax.swing.JTable tblPhongBan;
    private javax.swing.JTable tblTuoi;
    private javax.swing.JTable tblUngVien;
    private javax.swing.JTextField txtMaxLuong;
    private javax.swing.JTextField txtMaxTuoi;
    private javax.swing.JTextField txtMinLuong;
    private javax.swing.JTextField txtMinTuoi;
    // End of variables declaration//GEN-END:variables
    ThongKeDAO tkdao = new ThongKeDAO();
    ChucVuDAO cvdao = new ChucVuDAO();
    PhongBanDAO pbdao = new PhongBanDAO();
    
    public void selectTab(int index) {
        tabs.setSelectedIndex(index);
    }
    private void init(){
        fillComboBoxCv();
        fillComboBoxPb();
        fillTblHopDong();
        fillTblUngVien();
        fillTblTuoi();
        fillTblLuong();
        fillTblPhongBan();
        this.selectTab(0);
    }
    private void fillComboBoxCv(){
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboCv.getModel();
        model.removeAllElements();
        try {
            List<ChucVu> list = cvdao.selectAll();
            for (ChucVu cv: list) {
                model.addElement(cv.toTenCv());
            }
        }
        catch (Exception e) {
            Msgbox.alert(this, "Lỗi truy vấn dữ liệu");
            e.printStackTrace();
        }
    }
    private void fillComboBoxPb(){
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboPb.getModel();
        model.removeAllElements();
        try {
            List<PhongBan> list = pbdao.selectAll();
            for (PhongBan pb: list) {
                model.addElement(pb.toTenPb());
            }
        }
        catch (Exception e) {
            Msgbox.alert(this, "Lỗi truy vấn dữ liệu");
            e.printStackTrace();
        }        
    }
    private void fillTblUngVien(){
        DefaultTableModel model = (DefaultTableModel)tblUngVien.getModel();
        model.setRowCount(0);
        String selectedCv = (String) cboCv.getSelectedItem();
        System.out.println(selectedCv);
        List<Object[]> ds = tkdao.getUngVien(selectedCv);
        for(Object[] row:ds){
            model.addRow(new Object[]{row[0],row[1],row[2]});
        }
    }
    private void fillTblTuoi(){
        DefaultTableModel model = (DefaultTableModel)tblTuoi.getModel();
        model.setRowCount(0);
        int min, max;
        if (txtMinTuoi.getText().isEmpty()){
            min =18;
            txtMinTuoi.setText("18");
        }
        else{
            min = Integer.parseInt(txtMinTuoi.getText());
        }
        if (txtMaxTuoi.getText().isEmpty()){
            max = 60;
            txtMaxTuoi.setText("60");
        }
        else{
            max = Integer.parseInt(txtMaxTuoi.getText());
        }
        List<Object[]> ds = tkdao.getTuoi(min, max);
        for(Object[] row:ds){
            model.addRow(row);
        }
    }
    private void fillTblLuong(){
        DefaultTableModel model = (DefaultTableModel)tblLuong.getModel();
        model.setRowCount(0);
        int min, max;
        if (txtMinLuong.getText().isEmpty()){
            min =5000000;
            txtMinLuong.setText("5000000");
        }
        else{
            min = Integer.parseInt(txtMinLuong.getText());
        }
        if (txtMaxLuong.getText().isEmpty()){
            max = 50000000;
            txtMaxLuong.setText("50000000");
        }
        else{
            max = Integer.parseInt(txtMaxLuong.getText());
        }
        List<Object[]> ds = tkdao.getLuong(min, max);
        for(Object[] row:ds){
            model.addRow(row);
        }
    }
    
    private void fillTblHopDong(){
        DefaultTableModel model = (DefaultTableModel)tblHopDong.getModel();
        model.setRowCount(0);
        List<Object[]> ds = tkdao.getHopDong();
        for(Object[] row:ds){
            model.addRow(row);
        }
    }
    private void fillTblPhongBan(){
        DefaultTableModel model = (DefaultTableModel)tblPhongBan.getModel();
        model.setRowCount(0);
        String selectedPb = (String) cboPb.getSelectedItem();
        List<Object[]> ds = tkdao.getPhongBan(selectedPb);
        for(Object[] row:ds){
            model.addRow(row);
        }        
    }    
}
